# Generated by Django 5.0.4 on 2024-05-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='location',
        ),
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_of_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
